### ISSUE TITLE
Modular structure to make child projects

### ISSUE THREAD

**Issue by inureyes** [lablup/backend.ai-console#285]
Modular structure to make child projects. It is too hard to keep track on child projects such as backend.ai-pipeline.

## TODO

 * [x] Make components less dependent
 * [x] Remove backend.ai-console markups in common codes
 * [x] Make pipeline branch
 * [x] Make TFBox branch

**Comment by inureyes** [comment]
Works and spawns pyodide-console project
