### ISSUE TITLE
Unified event tasker

### ISSUE THREAD

**Issue by inureyes** [lablup/backend.ai-console#498]
* Implement unified event tasker for 20.03+

## TODO 
 * [x] Global event tasker
    * [x] Task class format
    * [x] Task pool with handlers
    * [x] Garbage collector
 * [x] Global progress indicator pool
 * [x] Migrate old codes to user global objects

 * Task monitor UI component will be handled as separate issue.
